# Config file for automatic testing at travis-ci.org

language: python
sudo: false

python:
    - "2.7"
    - "3.4"
    - "pypy"

install:
    - pip install --upgrade pip
    - pip install .
    - pip install coveralls

script:
    # - python -m unittest discover
    - coverage run --source=dragonlib ./setup.py test

after_success:
    - coveralls

# blacklist
branches:
  except:
    - wip
    - experimental

# whitelist
#branches:
#  only:
#    - master
#    - stable

notifications:
    irc: "irc.freenode.org#pylucid"
